package Nodespackage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ross Mcinerney
 */
public class NodesJframe extends javax.swing.JFrame
{

	Stack stack = new Stack();
	Node node = new Node();

	/**
	 * Creates new form NodesJframe
	 */
	public NodesJframe()
	{
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jCheckBox1 = new javax.swing.JCheckBox();
        outputjPane = new javax.swing.JPanel();
        inputPanel = new javax.swing.JPanel();
        inputjTextField = new javax.swing.JTextField();
        InsertjButton = new javax.swing.JButton();
        RemoveTopButton = new javax.swing.JButton();
        CheckEmptyjButton = new javax.swing.JButton();
        CheckFulljButton = new javax.swing.JButton();
        CurrentTopjButton = new javax.swing.JButton();
        NumberofitemsjButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        ClearStackjButton = new javax.swing.JButton();
        printStackButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        outputjPanel = new javax.swing.JPanel();
        ouputjTextArea = new javax.swing.JTextArea();

        jCheckBox1.setText("jCheckBox1");

        javax.swing.GroupLayout outputjPaneLayout = new javax.swing.GroupLayout(outputjPane);
        outputjPane.setLayout(outputjPaneLayout);
        outputjPaneLayout.setHorizontalGroup(
            outputjPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        outputjPaneLayout.setVerticalGroup(
            outputjPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stack Editor");

        inputjTextField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                inputjTextFieldActionPerformed(evt);
            }
        });

        InsertjButton.setText("Insert Top");
        InsertjButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                InsertjButtonActionPerformed(evt);
            }
        });

        RemoveTopButton.setText("Remove Top");
        RemoveTopButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                RemoveTopButtonActionPerformed(evt);
            }
        });

        CheckEmptyjButton.setText("Check Empty");
        CheckEmptyjButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CheckEmptyjButtonActionPerformed(evt);
            }
        });

        CheckFulljButton.setText("Check Full");
        CheckFulljButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CheckFulljButtonActionPerformed(evt);
            }
        });

        CurrentTopjButton.setText("Current Top");
        CurrentTopjButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CurrentTopjButtonActionPerformed(evt);
            }
        });

        NumberofitemsjButton.setText("Number of items");
        NumberofitemsjButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                NumberofitemsjButtonActionPerformed(evt);
            }
        });

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SearchButtonActionPerformed(evt);
            }
        });

        ClearStackjButton.setText("Clear Stack");

        printStackButton.setText("Print Stack");
        printStackButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                printStackButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CheckFulljButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClearStackjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumberofitemsjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(printStackButton, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RemoveTopButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckEmptyjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(CurrentTopjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputjTextField)
                    .addComponent(searchTextField)
                    .addComponent(InsertjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        inputPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CheckEmptyjButton, NumberofitemsjButton, RemoveTopButton, jButton3, printStackButton});

        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(inputjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsertjButton)
                .addGap(21, 21, 21)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberofitemsjButton)
                    .addComponent(RemoveTopButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(printStackButton)
                    .addComponent(CheckEmptyjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearStackjButton)
                    .addComponent(CurrentTopjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckFulljButton)
                    .addComponent(jButton3)))
        );

        ouputjTextArea.setEditable(false);
        ouputjTextArea.setColumns(20);
        ouputjTextArea.setRows(5);

        javax.swing.GroupLayout outputjPanelLayout = new javax.swing.GroupLayout(outputjPanel);
        outputjPanel.setLayout(outputjPanelLayout);
        outputjPanelLayout.setHorizontalGroup(
            outputjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ouputjTextArea, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        outputjPanelLayout.setVerticalGroup(
            outputjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ouputjTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(outputjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputjTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_inputjTextFieldActionPerformed
    {//GEN-HEADEREND:event_inputjTextFieldActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_inputjTextFieldActionPerformed

    private void CheckEmptyjButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CheckEmptyjButtonActionPerformed
    {//GEN-HEADEREND:event_CheckEmptyjButtonActionPerformed
		ouputjTextArea.setText("Stack is Empty " + stack.isEmpty());

    }//GEN-LAST:event_CheckEmptyjButtonActionPerformed

    private void CheckFulljButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CheckFulljButtonActionPerformed
    {//GEN-HEADEREND:event_CheckFulljButtonActionPerformed
//       isFull();
    }//GEN-LAST:event_CheckFulljButtonActionPerformed

    private void NumberofitemsjButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_NumberofitemsjButtonActionPerformed
    {//GEN-HEADEREND:event_NumberofitemsjButtonActionPerformed
		ouputjTextArea.setText("Stack size" + stack.size());
    }//GEN-LAST:event_NumberofitemsjButtonActionPerformed

    private void CurrentTopjButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CurrentTopjButtonActionPerformed
    {//GEN-HEADEREND:event_CurrentTopjButtonActionPerformed
		try
		{
			ouputjTextArea.setText("current top is " + stack.top());
		} catch (stackAcception e)
		{
			ouputjTextArea.setText(e.getMessage());
		}
    }//GEN-LAST:event_CurrentTopjButtonActionPerformed

    private void RemoveTopButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RemoveTopButtonActionPerformed
    {//GEN-HEADEREND:event_RemoveTopButtonActionPerformed
		try
		{
			stack.pop();
			ouputjTextArea.setText("current top is Deleted");
		} catch (stackAcception e)
		{
			ouputjTextArea.setText(e.getMessage());
		}
    }//GEN-LAST:event_RemoveTopButtonActionPerformed

    private void InsertjButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_InsertjButtonActionPerformed
    {//GEN-HEADEREND:event_InsertjButtonActionPerformed
		stack.push(inputjTextField.getText());
		inputjTextField.setText(" ");
    }//GEN-LAST:event_InsertjButtonActionPerformed

    private void printStackButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_printStackButtonActionPerformed
    {//GEN-HEADEREND:event_printStackButtonActionPerformed

		try
		{
			ouputjTextArea.setText(stack.Display());
		} catch (stackAcception e)
		{
			ouputjTextArea.setText(e.getMessage());
		}
    }//GEN-LAST:event_printStackButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SearchButtonActionPerformed
    {//GEN-HEADEREND:event_SearchButtonActionPerformed
		try
		{
			String target = searchTextField.getText();
			stack.search(target);
		} catch (stackAcception e)
		{
			ouputjTextArea.setText(e.getMessage());
		}

//		if(stack.search(target==true)){
//			ouputjTextArea.setText("found");
//		}
    }//GEN-LAST:event_SearchButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try
		{
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
			{
				if ("Nimbus".equals(info.getName()))
				{
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex)
		{
			java.util.logging.Logger.getLogger(NodesJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex)
		{
			java.util.logging.Logger.getLogger(NodesJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex)
		{
			java.util.logging.Logger.getLogger(NodesJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex)
		{
			java.util.logging.Logger.getLogger(NodesJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable()
		{
			public void run()
			{
				new NodesJframe().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckEmptyjButton;
    private javax.swing.JButton CheckFulljButton;
    private javax.swing.JButton ClearStackjButton;
    private javax.swing.JButton CurrentTopjButton;
    private javax.swing.JButton InsertjButton;
    private javax.swing.JButton NumberofitemsjButton;
    private javax.swing.JButton RemoveTopButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JTextField inputjTextField;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JTextArea ouputjTextArea;
    private javax.swing.JPanel outputjPane;
    private javax.swing.JPanel outputjPanel;
    private javax.swing.JButton printStackButton;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
